### ISSUE TITLE
运行 deployAndCallHelloWorld 报错

### ISSUE THREAD

**Issue by iamdevin** [FISCO-BCOS/spring-boot-starter#4]
java.lang.RuntimeException: org.fisco.bcos.web3j.protocol.exceptions.MessageDecodingException: {"error":{"code":-32601,"message":"METHOD_NOT_FOUND: The method being requested is not available on this server"},"id":1,"jsonrpc":"2.0"}

	at org.fisco.bcos.web3j.tx.Contract.deploy(Contract.java:363)
	at org.fisco.bcos.web3j.tx.Contract.lambda$deployRemoteCall$6(Contract.java:429)
	at org.fisco.bcos.web3j.protocol.core.RemoteCall.send(RemoteCall.java:31)
	at org.fisco.bcos.ContractTest.deployAndCallHelloWorld(ContractTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.fisco.bcos.web3j.protocol.exceptions.MessageDecodingException: {"error":{"code":-32601,"message":"METHOD_NOT_FOUND: The method being requested is not available on this server"},"id":1,"jsonrpc":"2.0"}

	at org.fisco.bcos.web3j.protocol.channel.ChannelEthereumService.send(ChannelEthereumService.java:67)
	at org.fisco.bcos.web3j.protocol.core.Request.send(Request.java:96)
	at org.fisco.bcos.web3j.tx.RawTransactionManager.signAndSend(RawTransactionManager.java:128)
	at org.fisco.bcos.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:95)
	at org.fisco.bcos.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:53)
	at org.fisco.bcos.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:45)
	at org.fisco.bcos.web3j.tx.Contract.executeTransaction(Contract.java:290)
	at org.fisco.bcos.web3j.tx.Contract.create(Contract.java:333)
	at org.fisco.bcos.web3j.tx.Contract.deploy(Contract.java:359)
	... 33 more

**Comment by iamdevin** [comment]
有没有维护人员。如何解决问题？

**Comment by yanyanho** [comment]
> 有没有维护人员。如何解决问题？

目前此版本只支持FISCO BCOS 2.0.
